import NavBar from '@/components/nav/NavBar';
import './globals.css';
import Header from '@/components/header/Header';
import Footer from '@/components/header/Footer';

export const metadata = {
  title: 'Pantelflora',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: ChildrenProps) => {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[1200px] md:mx-auto">
          <div className="mb-[25px]">
            <Header />
            <div>
              <div>
                <NavBar />
              </div>
            </div>
            {children}
            <div className="mb-[25px]" />
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
